Coop no login page and tool bar
projecthuman-repo/Regenquest-WebApp pull request #3
Opened 2023-02-12 22:57 UTC by geraldjet

2023-02-12 23:07 UTC, michael1999wang requested changes
Left some comments. The biggest thing is definitely prettier reformatting everything to a difference spacing though. Makes it very hard to keep track what is new and what is existing

2023-02-12 23:07 UTC, michael1999wang commented on frontend/src/components/Toolbar/index.tsx
> +  paddingLeft: 25,
Seems like your prettier settings might be on 2 spaces = a tab instead of 4 spaces. Try to change this and recommit the files as it bloats the diff and is harder to tell what changed.

2023-02-12 23:07 UTC, michael1999wang commented on frontend/src/pages/Coop/NoLogin.tsx
> +const Container = styled.div({});
Seems like you don't need this Container, can just use a regular div

2023-02-12 23:07 UTC, michael1999wang commented on frontend/src/styles/theme.ts
> +        },
Did you mean for these to be `styleOverrides`? They seem like they should be `defaultProps` instead. `styleOverrides` are only for CSS, which is probably why this isn't working

2023-02-12 23:07 UTC, michael1999wang commented on frontend/src/components/Toolbar/index.tsx
> +  variant: "h6",
I don't think you can do this since `styled` only works on CSS features. `variant` is prop that should be passed into the `Typography` element instead

2023-02-12 23:10 UTC, michael1999wang commented
Also, there's a merge request that will have to be dealt with before you can ship this code into mainline

2023-02-14 03:39 UTC, RayWangyangMa commented
I've fix the conflicts, and it looks good to me

2023-02-14 03:41 UTC, RayWangyangMa approved these changes

2023-02-14 03:51 UTC, RayWangyangMa approved these changes

2023-02-16 01:38 UTC, closed without merging