Programs dev branch - Create flow
projecthuman-repo/Regenquest-WebApp pull request #5
Opened 2023-02-16 02:41 UTC by Ali7109

"Create a new program" routing setup complete. Implementation for "Basic information complete. Rest of the pages in "Create program" are to be implemented.

2023-02-18 19:20 UTC, michael1999wang requested changes
Some minor changes, but very well done overall

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/index.tsx
> +
nit: you can make an index.ts file at pages/Programs/CreateProgram and export these all in 1 line

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/index.tsx
> +
Can look at some of the other folders to see how we've done it

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/index.tsx
> +				path: "basic-information",
Not sure on this one, but do you need a / at the beginning?

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/CreateProgram/BasicInformation/index.tsx
> +});
nit: Usually better practice to define the helper components above

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/CreateProgram/Operations/index.tsx
> +	return <div>Operaitons</div>;
Typo

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/CreateProgram/index.tsx
> +						>
Use a styled component here. We want to avoid inline styling as much as possible since it presents risk for Cross-Site-Scripting attacks

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/HashtagSearch.tsx
> +const HashtagSearch = (props: { hashtags: string[] }) => {
It's good to define the prop types in a separate types object and export it as well. See some other components on how it's usually done

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/ProgramCreateProgress/index.tsx
> +		>
Styled component here, inline styles present risk for XSS attacks

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/ProgramCreateProgress/index.tsx
> +const ProgramCreateProgress = (props: { pgnum: number }) => {
I believe there's a Stepper component in material ui that you can use instead

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/ProgramCreateProgress/styles.css
> +.BallStyles {
Do we need this css file or can we do so with styled components? Just for consistency

2023-02-18 19:20 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/RadioGroupField.tsx
> +interface Props {
Better to change this to RadioGroupFieldProps and export it. External files might need to know the typing as well and shouldn't definite it again manually

2023-02-19 09:40 UTC, geraldjet approved these changes

2023-02-19 15:12 UTC, Ali7109 commented on frontend/src/index.tsx
> +				path: "basic-information",
I was thinking the same thing, but for some reason it only works without the "/" for the children.

2023-02-19 17:22 UTC, Ali7109 commented on frontend/src/pages/Programs/CreateProgram/BasicInformation/index.tsx
> +});
I repositioned the helper components.

2023-02-19 17:22 UTC, Ali7109 commented on frontend/src/pages/Programs/CreateProgram/index.tsx
> +						>
I have designed individual styled Buttons for "Back" and "Next" now.

2023-02-19 17:23 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/HashtagSearch.tsx
> +const HashtagSearch = (props: { hashtags: string[] }) => {
The types are now exported and as an individual object.

2023-02-19 17:24 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/ProgramCreateProgress/index.tsx
> +		>
I have used the MUIStepper now, so this has been removed entirely.

2023-02-19 17:25 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/ProgramCreateProgress/index.tsx
> +const ProgramCreateProgress = (props: { pgnum: number }) => {
Thanks! Now its using the MUIStepper, looks alot cleaner, however theres no working method to adjust the color. Will need to adjust that soon.

2023-02-19 17:25 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/ProgramCreateProgress/styles.css
> +.BallStyles {
I have used the MUIStepper now, so this has been removed entirely.

2023-02-19 17:26 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/RadioGroupField.tsx
> +interface Props {
The types are now exported as a seperate object.

2023-02-20 06:01 UTC, michael1999wang requested changes
Just the one thing about the ThemeProvider

2023-02-20 06:01 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/ProgressStepper.tsx
> +});
We should already have a theme in the styles folder. We should avoid having multiple instances of the ThemeProvider in the same application. You can move these styles over there

2023-02-20 06:01 UTC, michael1999wang commented on frontend/src/pages/Programs/ProgramComponents/ProgressStepper.tsx
> +			<ThemeProvider theme={stepTheme}>
Can remove this after you address the comment above

2023-02-20 18:42 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/ProgressStepper.tsx
> +});
That makes sense, sorry about that. Should be in the styles theme.ts file now.

2023-02-20 18:43 UTC, Ali7109 commented on frontend/src/pages/Programs/ProgramComponents/ProgressStepper.tsx
> +			<ThemeProvider theme={stepTheme}>
Removed.

2023-02-20 19:06 UTC, michael1999wang approved these changes
LGTM

2023-02-20 19:16 UTC, merged